version: '2'
services:
    db_mariadb2:
       image: mariadb
       ports:
          - "3306:3306"
       volumes:
       - "./.srv/docker/redmine/mysql:/var/lib/mysql"
       environment:
          MYSQL_ROOT_PASSWORD: Cfrehf26
    web_nginx80:
       image: nginx80
       ports:
          - "80:80"
    web_nginx443:
       image: nginx443
       ports:
          - "443:443"
    redmine_36:
       depends_on:
          - db_mariadb2
       image: alexonixon/docker_redmine
       ports:
          - "172.17.0.1:3128:80"
       volumes:
          - "./.srv/docker/redmine/redmine:/home/redmine/data"
       environment:
          DB_NAME: redmine
          DB_USER: redmine
          DB_HOST: 172.17.0.1
          DB_PASS: 777