TYPE=VIEW
query=select `t_e`.`id` AS `id`,`u`.`firstname` AS `first_name`,`u`.`lastname` AS `last_name`,concat(`u`.`lastname`,\' \',`u`.`firstname`) AS `full_name`,concat(`user`.`lastname`,\' \',`user`.`firstname`) AS `groups`,`p`.`name` AS `project`,`t_e`.`issue_id` AS `issue`,`i`.`subject` AS `subject`,`i`.`description` AS `description`,concat(`usr`.`lastname`,\' \',`usr`.`firstname`) AS `assigned_to`,date_format(`t_e`.`spent_on`,\'%Y-%m-%d\') AS `created_on`,`e`.`name` AS `priority`,`t`.`name` AS `tracker`,`t_e`.`hours` AS `hours`,`i`.`done_ratio` AS `done_ratio`,date_format(`i`.`closed_date`,\'%Y-%m-%d\') AS `closed_on` from ((((((((`redmine`.`time_entries` `t_e` join `redmine`.`users` `u` on((`t_e`.`user_id` = `u`.`id`))) join `redmine`.`groups_users` `g_u` on((`u`.`id` = `g_u`.`user_id`))) join `redmine`.`users` `user` on((`g_u`.`group_id` = `user`.`id`))) join `redmine`.`projects` `p` on((`t_e`.`project_id` = `p`.`id`))) join `redmine`.`issues` `i` on((`t_e`.`issue_id` = `i`.`id`))) join `redmine`.`enumerations` `e` on((`e`.`id` = `i`.`priority_id`))) join `redmine`.`trackers` `t` on((`t`.`id` = `i`.`tracker_id`))) left join `redmine`.`users` `usr` on((`usr`.`id` = `i`.`assigned_to_id`)))
md5=e16965a7d747957508a8ca9c8ebb4f6c
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2016-08-05 22:02:41
create-version=2
source=select `t_e`.`id` AS `id`,`u`.`firstname` AS `first_name`,`u`.`lastname` AS `last_name`,concat(`u`.`lastname`,\' \',`u`.`firstname`) AS `full_name`,concat(`user`.`lastname`,\' \',`user`.`firstname`) AS `groups`,`p`.`name` AS `project`,`t_e`.`issue_id` AS `issue`,`i`.`subject` AS `subject`,`i`.`description` AS `description`,concat(`usr`.`lastname`,\' \',`usr`.`firstname`) AS `assigned_to`,date_format(`t_e`.`spent_on`,\'%Y-%m-%d\') AS `created_on`,`e`.`name` AS `priority`,`t`.`name` AS `tracker`,`t_e`.`hours` AS `hours`,`i`.`done_ratio` AS `done_ratio`,date_format(`i`.`closed_date`,\'%Y-%m-%d\') AS `closed_on` from ((((((((`time_entries` `t_e` join `users` `u` on((`t_e`.`user_id` = `u`.`id`))) join `groups_users` `g_u` on((`u`.`id` = `g_u`.`user_id`))) join `users` `user` on((`g_u`.`group_id` = `user`.`id`))) join `projects` `p` on((`t_e`.`project_id` = `p`.`id`))) join `issues` `i` on((`t_e`.`issue_id` = `i`.`id`))) join `enumerations` `e` on((`e`.`id` = `i`.`priority_id`))) join `trackers` `t` on((`t`.`id` = `i`.`tracker_id`))) left join `users` `usr` on((`usr`.`id` = `i`.`assigned_to_id`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `t_e`.`id` AS `id`,`u`.`firstname` AS `first_name`,`u`.`lastname` AS `last_name`,concat(`u`.`lastname`,\' \',`u`.`firstname`) AS `full_name`,concat(`user`.`lastname`,\' \',`user`.`firstname`) AS `groups`,`p`.`name` AS `project`,`t_e`.`issue_id` AS `issue`,`i`.`subject` AS `subject`,`i`.`description` AS `description`,concat(`usr`.`lastname`,\' \',`usr`.`firstname`) AS `assigned_to`,date_format(`t_e`.`spent_on`,\'%Y-%m-%d\') AS `created_on`,`e`.`name` AS `priority`,`t`.`name` AS `tracker`,`t_e`.`hours` AS `hours`,`i`.`done_ratio` AS `done_ratio`,date_format(`i`.`closed_date`,\'%Y-%m-%d\') AS `closed_on` from ((((((((`redmine`.`time_entries` `t_e` join `redmine`.`users` `u` on((`t_e`.`user_id` = `u`.`id`))) join `redmine`.`groups_users` `g_u` on((`u`.`id` = `g_u`.`user_id`))) join `redmine`.`users` `user` on((`g_u`.`group_id` = `user`.`id`))) join `redmine`.`projects` `p` on((`t_e`.`project_id` = `p`.`id`))) join `redmine`.`issues` `i` on((`t_e`.`issue_id` = `i`.`id`))) join `redmine`.`enumerations` `e` on((`e`.`id` = `i`.`priority_id`))) join `redmine`.`trackers` `t` on((`t`.`id` = `i`.`tracker_id`))) left join `redmine`.`users` `usr` on((`usr`.`id` = `i`.`assigned_to_id`)))
mariadb-version=100116
